/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PdfComponent {
    }
}
declare global {
    interface HTMLPdfComponentElement extends Components.PdfComponent, HTMLStencilElement {
    }
    var HTMLPdfComponentElement: {
        prototype: HTMLPdfComponentElement;
        new (): HTMLPdfComponentElement;
    };
    interface HTMLElementTagNameMap {
        "pdf-component": HTMLPdfComponentElement;
    }
}
declare namespace LocalJSX {
    interface PdfComponent {
    }
    interface IntrinsicElements {
        "pdf-component": PdfComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pdf-component": LocalJSX.PdfComponent & JSXBase.HTMLAttributes<HTMLPdfComponentElement>;
        }
    }
}
